services:
  mysql:
    image: mysql:8.4.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: play
      MYSQL_USER: play
      MYSQL_PASSWORD: secret
    restart: always
